version: '3.9'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    # Uncomment the following lines if you have environment variables in a .env file
    env_file:
      - app/services/.env
    volumes:
      - .:/app
    
